server:
  port: 8080

spring:
  application:
    name: crawling

  security:
    user:
      name: root
      password: 1234 # Spring Security 초기 유저 정보

#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/sample
#    username: root
#    password: 1234
#
#  jpa:
#    hibernate:
#      ddl-auto: update # 엔티티로 등록된 클래스와 매핑되는 테이블 자동 생성 주석해도 됩니다.
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#        # 자바에서 카멜로 필드 작성하면 DB에 스네이크로 기록
#    properties:
#      hibernate:
#        format_sql: true # SQL 이쁘게 보기
#        show_sql: true # SQL 보기

